# Travis-CI file for weio
language: python

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
os: 
 - linux
sudo: true

install:
  - pip install -r requirements.txt
  - pip install -r requirements_optional.txt

script: 
  - make test

